version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    depends_on:
      neo4j_db:
        condition: service_healthy
    volumes:
      - myapp_config:/home/app

  neo4j_db:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/1234
      - NEO4JLABS_PLUGINS=["apoc"]
    healthcheck:
      test: wget http://neo4j_db:7474 || exit 1
      interval: 3s
      timeout: 1s
      retries: 20
      start_period: 10s

volumes:
  neo4j_data:
  neo4j_logs:
  myapp_config: